dashboard/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('subjects', views.subjects_page, name='subjects'),
    path('utils/', views.utils, name='utils'),
    path('<code>/', views.detail, name='detail'),
    path('utils/<action>', views.utils, name='utils'),
    path('<code>/<action>', views.detail_action, name='detail'),
    path('admin/', admin.site.urls),
    path('set_timezone', views.set_timezone, name='set_timezone'),
]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path as url
from django.views.generic import TemplateView

from mysite import settings

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='dashboard/index.html'), name='home'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
# HOW TO CHANGE MODEL:
# Change your models (in models.py).
# Run python manage.py makemigrations to create migrations for those changes
# --> python manage.py makemigrations dashboard
# Run python manage.py migrate to apply those changes to the database.
# --> python manage.py sqlmigrate dashboard 0001
# --> python manage.py migrate

import os
from datetime import timedelta, datetime
from os import path
from pathlib import Path

import pytz
from django.core.validators import FileExtensionValidator
from django.db import models

from dashboard.logic.features_extraction.norms import sol, awk5plus, waso, se
from dashboard.logic.features_extraction.utils import safe_div
from mysite.settings import MEDIA_ROOT


class Subject(models.Model):
    code = models.CharField('subject code', max_length=50, unique=True)
    age = models.SmallIntegerField('age (years)')
    SEX = [
        ('M', 'Male'),
        ('F', 'Female')
    ]
    sex = models.CharField('sex', max_length=1, choices=SEX)
    creation_date = models.DateField('creation date', auto_now_add=True)
    pPD = models.BooleanField('probable parkinson disease', default=False)
    pMCI = models.BooleanField('probable mild cognitive impairment', default=False)
    HC = models.BooleanField('healthy control', default=False)
    SA = models.BooleanField('sleep apnea', default=False)
    predPDorMCI = models.BooleanField('probable parkinson disease', default=False)
    DIAGNOSIS = [
        ('D', 'preDLB'),
        ('N', 'NonHC'),
        ('H', 'HC'),
        ('U', 'Unknown')
    ]
    diagnosis = models.CharField('diagnosis', max_length=1, choices=DIAGNOSIS, default='U')
    diagnosis2024 = models.CharField('diagnosis', max_length=1, choices=DIAGNOSIS, default='U')

    def __str__(self):
        return self.code

    def is_test(self):
        return CsvData.objects.filter(subject=self).filter(training_data=True).exists()

    @property
    def export_path(self):
        return path.join(MEDIA_ROOT, 'export', self.code)

    @property
    def export_name(self):
        return path.join(self.export_path, f'{self.code}_report')


class CsvData(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    BODY_LOCATIONS = [
        ('L', 'Left wrist'),
        ('R', 'Right wrist'),
        ('O', 'Other')
    ]
    body_location = models.CharField('body location', max_length=1, choices=BODY_LOCATIONS, default='L')
    data = models.FileField('data', upload_to='data/', validators=[FileExtensionValidator(["csv"])])
    description = models.CharField('description', max_length=255, blank=True)
    creation_date = models.DateField('date of upload', auto_now_add=True)
    training_data = models.BooleanField('training data', default=False)
    end_date = models.DateTimeField('end date to process', null=True, blank=True)
    dreamt_data = models.BooleanField('dreamt data', default=False)

    @property
    def filename(self):
        return path.basename(self.data.name)

    @property
    def cached_prediction_path(self):
        data_path = Path(self.data.path).resolve()
        folder = data_path.parent.parent / 'predictions'
        folder.mkdir(exist_ok=True)
        return str(folder / f'{data_path.name}.pkl')

    @property
    def x_data_path(self):
        data_path = Path(self.data.path).resolve()
        folder = data_path.parent.parent / 'cache'
        folder.mkdir(exist_ok=True)
        return str(folder / f'{data_path.name}.xlsx')

    @property
    def excel_prediction_path(self):
        data_path = Path(self.data.path).resolve()
        folder = data_path.parent.parent / 'predictions-excel'
        folder.mkdir(exist_ok=True)
        return str(folder / f'{data_path.name}.xlsx')

    @property
    def excel_prediction_url(self):
        if path.exists(self.excel_prediction_path):
            return self.data.storage.url(self.excel_prediction_path)
        else:
            return ''

    @property
    def sleeppy_dir(self):
        data_path = Path(self.data.path).resolve()
        folder = data_path.parent.parent / 'sleeppy'
        folder.mkdir(exist_ok=True)
        return str(folder)

    def __str__(self):
        return f'CSV data {self.filename} from subject {self.subject.code}'


class PsData(models.Model):
    csv_data = models.OneToOneField(CsvData, on_delete=models.CASCADE, primary_key=True)
    data = models.FileField('data', upload_to='ps/', validators=[FileExtensionValidator(["txt"])])
    creation_date = models.DateField('date of upload', auto_now_add=True)

    @property
    def filename(self):
        return path.basename(self.data.name)

    def __str__(self):
        return f'Polysomnography data {self.filename} for CSV data {self.csv_data.filename}'


class SleepDiaryDay(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    creation_date = models.DateField('date of upload', auto_now_add=True)
    date = models.DateField('date')

    day_sleep_count = models.PositiveSmallIntegerField('count of sleep during day', blank=True)
    day_sleep_time = models.PositiveSmallIntegerField('duration of sleep during day (min)', blank=True, null=True)
    alcohol_count = models.PositiveSmallIntegerField('number of alcoholic beverages', blank=True)
    alcohol_time = models.TimeField('time of the last alcoholic beverage', blank=True, null=True)
    caffeine_count = models.PositiveSmallIntegerField('number of caffeine drinks', blank=True)
    caffeine_time = models.TimeField('time of the last caffeine drink', blank=True, null=True)
    sleeping_pill = models.BooleanField('sleeping pill')

    sleep_time = models.TimeField('try to fall asleep time')
    sleep_duration = models.TimeField('expected fall asleep time')
    wake_count = models.PositiveSmallIntegerField('number of wake ups during night')
    wake_time = models.TimeField('wake up time')
    get_up_time = models.TimeField('get up time')

    SLEEP_QUALITY = [
        (1, 'Very poor'),
        (2, 'Poor'),
        (3, 'Fair'),
        (4, 'Good'),
        (5, 'Very good'),
    ]
    sleep_quality = models.PositiveSmallIntegerField('sleep quality', choices=SLEEP_QUALITY, blank=True, null=True)
    REST_QUALITY = [
        (1, 'Not at all rested'),
        (2, 'Slightly rested'),
        (3, 'Somehow rested'),
        (4, 'Well-rested'),
        (5, 'Very well-rested')
    ]
    rest_quality = models.PositiveSmallIntegerField('rest quality', choices=REST_QUALITY, blank=True, null=True)
    note = models.CharField('note', max_length=255, blank=True)

    def _with_date(self, time):
        if 0 <= time.hour < 12:
            return datetime.combine(self.date + timedelta(days=1), time)
        return datetime.combine(self.date, time)

    def with_date_base_on_previous(self, time, previous):
        maybe = self._with_date(time)
        if maybe < previous:
            return datetime.combine(maybe.date() + timedelta(days=1), time)
        else:
            return maybe

    @property
    def t1(self):
        return self._with_date(self.sleep_time)

    @property
    def t2(self):
        return self.with_date_base_on_previous(self.sleep_duration, self.t1)

    @property
    def t3(self):
        return self.with_date_base_on_previous(self.wake_time, self.t2)

    @property
    def t4(self):
        return self.with_date_base_on_previous(self.get_up_time, self.t3)

    def __str__(self):
        return f'Subject: {self.subject.code} | Date: {self.date} | {self.info}'

    @property
    def wake_intervals(self):
        return WakeInterval.objects.filter(sleep_diary_day=self)

    @property
    def wake_intervals_str(self):
        s = ''
        for w in self.wake_intervals:
            s += f'{w} | '
        return s

    @property
    def info(self):
        return f'Bed time: {self.sleep_time} ' \
               f'| Sleep onset: {self.sleep_duration} ' \
               f'| Wake count: {self.wake_count} ' \
               f'| Wake ups: {self.wake_intervals_str}' \
               f'| Sleep end: {self.wake_time} ' \
               f'| Get up time: {self.get_up_time}'

    @staticmethod
    def convert(n):
        return timedelta(seconds=n)

    @property
    def tib(self):
        return (self.t4 - self.t1).seconds

    @property
    def sol(self):
        return (self.t2 - self.t1).seconds

    @property
    def waso(self):
        wake = 0
        for i in self.wake_intervals:
            wake += i.duration.seconds
        return wake

    @property
    def wasf(self):
        return (self.t4 - self.t3).seconds

    @property
    def tst(self):
        return self.tib - (self.sol + self.waso + self.wasf)

    @property
    def wb(self):
        return len(self.wake_intervals)

    @property
    def awk5plus(self):
        count = 0
        for i in self.wake_intervals:
            if i.duration.seconds >= 300:
                count += 1
        return count

    @property
    def se(self):
        return safe_div(self.tst, self.tib) * 100

    @property
    def sf(self):
        return safe_div(self.wb, (self.tst / 3600))

    @property
    def sol_norm(self):
        return sol(self.subject.age, self.sol)

    @property
    def awk5plus_norm(self):
        return awk5plus(self.subject.age, self.awk5plus)

    @property
    def waso_norm(self):
        return waso(self.subject.age, self.waso)

    @property
    def se_norm(self):
        return se(self.subject.age, self.se)


class WakeInterval(models.Model):
    sleep_diary_day = models.ForeignKey(SleepDiaryDay, on_delete=models.CASCADE)
    creation_date = models.DateField('creation date', auto_now_add=True)
    start = models.TimeField('start')
    end = models.TimeField('stop')

    @property
    def duration(self):
        t1 = timedelta(hours=self.start.hour, minutes=self.start.minute)
        t2 = timedelta(hours=self.end.hour, minutes=self.end.minute)
        duration = t2 - t1
        return duration if duration.seconds > 60 else timedelta(minutes=1)

    @property

dashboard/templates/dashboard/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

{% include "dashboard/head.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/default.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/fonts.css' %}" media="all">
<style>
    table {
        border-collapse: collapse;
        width: 92%;
        margin: 0% 4%;
    }

    td, th {
        border: 1px solid #FFF;
        text-align: left;
        padding: 8px;
        color: #0c498b;
    }

    tr:nth-child(even) {
        background-color: #fdc601;
    }

    tr:nth-child(odd) {
        background-color: #FEDD67;
    }
</style>


<div id="header-wrapper">
    <div id="header" class="container">
        <div id="menu">
            <ul>
                <li><a href="{% url 'dashboard:index' %}" accesskey="1" title="">Homepage</a></li>
                <li class="current_page_item"><a href="{% url 'dashboard:subjects' %}" accesskey="2"
                                                 title="">Dashboard</a></li>
                <li><a href="{% url 'admin:index' %}" accesskey="3" title="">Administration</a></li>
                {% if request.user.is_superuser %}
                    <li><a href="{% url 'dashboard:utils' %}" accesskey="4" title="">Utils</a></li>
                {% endif %}
            </ul>
        </div>
        {% include "dashboard/logo.html" %}
    </div>
</div>
<div id="wrapper3">
    <div id="portfolio" class="container">
        {% if subject %}
            <div class="title">
                <h2>Subject detail</h2>
                <span class="byline">Code: {{ subject.code }}</span>
                <p>| Age: {{ subject.age }} | Sex: {{ subject.get_sex_display }}
                    | Sleep disorder: {{ subject.sleep_disorder }} | Diagnosis: {{ subject.diagnosis }}
                    | Creation date: {{ subject.creation_date }} | RBD-SQ score: {{ rbdsq }}
                    | Parkinson disease or Mild cognitive impairment: {{ subject.predPDorMCI }} |</p>
                <p>
                    <a href="{% url 'dashboard:detail' subject.code 'export' %}" class="button button-small">Export to
                        PDF report</a>
                    <a href="{% url 'dashboard:subjects' %}" class="button button-small">Back to dashboard</a>
                </p>

            </div>
            <div class="title">
            {% if data %}
                <h3>Actigraphy data</h3>
                {% for tup in data %}
                    <div>
                        {% autoescape off %}
                            {{ tup.0 }}
                        {% endautoescape %}
                        {% if tup.2 %}
                            Estimated: {{ tup.2 }}<br/>
                        {% endif %}
                        {% if tup.3 %}
                            Diary: {{ tup.3 }}<br/>
                        {% endif %}
                        <p><a href="{{ tup.1 }}" class="button button-small" download>Download data</a></p>
                    </div>
                {% endfor %}
            {% else %}
                <p>No data for this subject yet.</p>
            {% endif %}

            {% if diary %}
                <div class="title">
                    <h3>Sleep diary</h3>
                </div>
                <table>
                    <tr>
                        <th> Date</th>
                        <th> Day sleep nr.</th>
                        <th> Day sleep time</th>
                        <th> Alcohol nr.</th>
                        <th> Alcohol time</th>
                        <th> Caffeine nr.</th>
                        <th> Caffeine time</th>
                        <th> Sleeping pill</th>
                        <th> Bed time</th>
                        <th> Sleep time</th>
                        <th> Wake ups nr.</th>
                        <th> Awake time</th>
                        <th> Get up time</th>
                        <th> Sleep quality</th>
                        <th> Rest quality</th>
                    </tr>
                    {% for day in diary %}
                        <tr>
                            <td> {{ day.date }} </td>
                            <td> {{ day.day_sleep_count }} </td>
                            <td> {{ day.day_sleep_time }} </td>
                            <td> {{ day.alcohol_count }} </td>
                            <td> {{ day.alcohol_time }} </td>
                            <td> {{ day.caffeine_count }} </td>
                            <td> {{ day.caffeine_time }} </td>
                            <td> {{ day.sleeping_pill }} </td>
                            <td> {{ day.sleep_time }} </td>
                            <td> {{ day.sleep_duration }} </td>
                            <td> {{ day.wake_count }} </td>
                            <td> {{ day.wake_time }} </td>
                            <td> {{ day.get_up_time }} </td>
                            <td> {{ day.get_sleep_quality_display }} </td>
                            <td> {{ day.get_rest_quality_display }} </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>No sleep diary entries.</p>
            {% endif %}

        {% else %}
            <div class="title">
                <h2>Subject does not found</h2>
                <span class="byline">Please, select valid subject</span>
            </div>
        {% endif %}
        </div>
    </div>
</div>

<div>{% include "dashboard/license.html" %}</div>

</body>
</html>

dashboard/templates/dashboard/head.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Intelligent sleep monitoring tool</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>

    {% load static %}
    <!--[if IE 6]>
    <link href="default_ie6.css" rel="stylesheet" type="text/css"/><![endif]-->

    <!-- icons -->
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'dashboard/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'dashboard/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'dashboard/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'dashboard/favicon/favicon-16x16.png' %}">

</head>
</html>

dashboard/templates/dashboard/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

{% include "dashboard/head.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/default.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/fonts.css' %}" media="all">

<body>
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="menu">
            <ul>
                <li class="current_page_item"><a href="{% url 'dashboard:index' %}" accesskey="1" title="">Homepage</a>
                </li>
                <li><a href="{% url 'dashboard:subjects' %}" accesskey="2" title="">Dashboard</a></li>
                <li><a href="{% url 'admin:index' %}" accesskey="3" title="">Administration</a></li>
                {% if request.user.is_superuser %}
                    <li><a href="{% url 'dashboard:utils' %}" accesskey="4" title="">Utils</a></li>
                {% endif %}
            </ul>
        </div>
        {% include "dashboard/logo.html" %}
        <a href="https://www.interreg-central.eu/Content.Node/niCE-life.html" rel="nofollow">
            <img src="{% static 'dashboard/images/logo.png' %}"/>
        </a>
    </div>
</div>
<div id="wrapper1">
    <div id="welcome" class="container">
        <div id="welcome" class="container">
            <div class="title">
                <h2>Welcome to Intelligent sleep monitoring system</h2>
                <span class="byline">A system created thanks to
                    <a href="https://www.interreg-central.eu/Content.Node/niCE-life.html">
                        niCE-life, INTERREG CENTRAL EUROPE</a>
                    support
                </span>
            </div>
            <div class="content">
                <p>This site was created to manage study about sleep disorders using
                    <a href="https://www.activinsights.com/products/geneactiv/">GENEActiv actigraph</a> and to present
                    its results. Site consists of this parts:
                    <a href="{% url 'dashboard:subjects' %}" title="">Dashboard</a>,
                    that presents the results of the study subject by subject.
                    <a href="admin:index" title="">Administration</a> site used to login &amp manage the system.
                    Administrators of the system can access <a href="{% url 'dashboard:utils' %}">Utils</a> page that
                    contains commands to perform batch operations.
                </p>

                <a href="{% url 'dashboard:subjects' %}" class="button">Dashboard</a>
            </div>
        </div>
    </div>
</div>
<div id="wrapper3">
    <div id="portfolio" class="container">
        <div class="title">
            <h2>Searching for more information?</h2>
            <span class="byline">Those are the related web pages to help you find more info</span></div>
        <div class="column">
            <div class="box">
                <a href="https://www.vutbr.cz/">
                    <img src="{% static 'dashboard/images/vutbr.png' %}" alt="" class="image image-full"/>
                </a>
                <h3>Brno University of Technology</h3>
                <p>See the details about the institution that stands behind the system.</p>
                <a href="https://www.vutbr.cz/" class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box">
                <a href="https://bdalab.utko.feec.vutbr.cz/"><img
                        src="{% static 'dashboard/images/bda.png' %}" alt="" class="image image-full"/></a>
                <h3>BDALab</h3>
                <p>Find more information about team that created the system.</p>
                <a href="https://bdalab.utko.feec.vutbr.cz/" class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box">
                <a href="https://www.interreg-central.eu/Content.Node/niCE-life.html"><img
                        src="{% static 'dashboard/images/nicelife.png' %}" alt="" class="image image-full"/></a>
                <h3>niCE-life</h3>
                <p>Project supported by Interreg CENTRAL EUROPE, innovation and knowledge development.</p>
                <a href="https://www.interreg-central.eu/Content.Node/niCE-life.html" class="button button-small">Visit
                    site</a>
            </div>
        </div>
        <div class="column">
            <div class="box"><a href="https://github.com/BDALab/sleep-analysis-system"><img
                    src="{% static 'dashboard/images/github.png' %}" alt="" class="image image-full"/></a>
                <h3>Source codes</h3>
                <p>Source codes of the project are accessible via its Github repository.</p>
                <a href="https://github.com/BDALab/sleep-analysis-system" class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box"><a href="https://www.activinsights.com/"><img
                    src="{% static 'dashboard/images/activinsights.png' %}" alt="" class="image image-full"/></a>
                <h3>Activinsights</h3>
                <p>Visit the website of the manufacturer of GENEActiv actigraph.</p>
                <a href="https://www.activinsights.com/" class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box"><a href="https://www.nature.com/articles/s41598-018-31266-z#data-availability"><img
                    src="{% static 'dashboard/images/dataset.png' %}" alt="" class="image image-full"/></a>
                <h3>Dataset</h3>
                <p>Open source dataset of actigraphy and polysomnography data.</p>
                <a href="https://www.nature.com/articles/s41598-018-31266-z#data-availability"
                   class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box"><a href="https://www.djangoproject.com/"><img
                    src="{% static 'dashboard/images/django.png' %}" alt="" class="image image-full"/></a>
                <h3>Django</h3>
                <p>System was created based on the web framework Django.</p>
                <a href="https://www.djangoproject.com/" class="button button-small">Visit site</a>
            </div>
        </div>
        <div class="column">
            <div class="box"><a href="https://xgboost.ai/"><img
                    src="{% static 'dashboard/images/xgboost.png' %}" alt="" class="image image-full"/></a>
                <h3>XGBoost</h3>
                <p>Predictions of sleep are made with XGBoost algorithm.</p>
                <a href="https://xgboost.ai/" class="button button-small">Visit site</a>
            </div>
        </div>
    </div>
</div>

{% include "dashboard/license.html" %}
</body>
</html>

dashboard/templates/dashboard/subjects.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

{% include "dashboard/head.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/default.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/fonts.css' %}" media="all">

<body>
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="menu">
            <ul>
                <li><a href="{% url 'dashboard:index' %}" accesskey="1" title="">Homepage</a></li>
                <li class="current_page_item"><a href="{% url 'dashboard:subjects' %}" accesskey="2"
                                                 title="">Dashboard</a></li>
                <li><a href="{% url 'admin:index' %}" accesskey="3" title="">Administration</a></li>
                {% if request.user.is_superuser %}
                    <li><a href="{% url 'dashboard:utils' %}" accesskey="4" title="">Utils</a></li>
                {% endif %}
            </ul>
        </div>
        {% include "dashboard/logo.html" %}
    </div>
</div>
<div id="wrapper3">
    <div id="portfolio" class="container">
        <div class="title">
            <h2>Subjects of study</h2>
            <span class="byline">Manage subjects of your study</span>
        </div>
        {% if subjects %}
            {% for s in subjects %}
                <div class="small-column">
                    <div class="box">
                        <a href="{% url 'dashboard:detail' s.code %}">
                            {% if s.sex == 'M' and s.predPDorMCI %}
                                <img src="{% static 'dashboard/images/man_red.png' %}" alt=""
                                     class="image image-smaller"/>
                            {% elif s.sex == 'F' and s.predPDorMCI %}
                                <img src="{% static 'dashboard/images/woman_red.png' %}" alt=""
                                     class="image image-smaller"/>
                            {% elif s.sex == 'M' and not s.predPDorMCI %}
                                <img src="{% static 'dashboard/images/man.png' %}" alt="" class="image image-smaller"/>
                            {% elif s.sex == 'F' and not s.predPDorMCI %}
                                <img src="{% static 'dashboard/images/woman.png' %}" alt=""
                                     class="image image-smaller"/>
                            {% endif %}
                        </a>
                        <h3>Code: {{ s.code }}</h3>
                        <p>Creation date: {{ s.creation_date }}</p>
                        <a href="{% url 'dashboard:detail' s.code 'export' %}" class="button button-small">Export</a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No subjects are available. Add some subjects to your study.</p>
        {% endif %}
    </div>
</div>

{% include "dashboard/license.html" %}
</body>
</html>

dashboard/templates/dashboard/timezone.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

{% include "dashboard/head.html" %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/default.css' %}" media="all">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/fonts.css' %}" media="all">

<body>
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="menu">
            <ul>
                <li class="current_page_item"><a href="{% url 'dashboard:index' %}" accesskey="1" title="">Homepage</a>
                </li>
                <li><a href="{% url 'dashboard:subjects' %}" accesskey="2" title="">Dashboard</a></li>
                <li><a href="{% url 'admin:index' %}" accesskey="3" title="">Administration</a></li>
                {% if request.user.is_superuser %}
                    <li><a href="{% url 'dashboard:utils' %}" accesskey="4" title="">Utils</a></li>
                {% endif %}
            </ul>
        </div>
        {% include "dashboard/logo.html" %}
    </div>
</div>

{% load tz %}
{% get_current_timezone as TIME_ZONE %}
<form action="{% url 'dashboard:set_timezone' %}" method="POST">
    {% csrf_token %}
    <label for="timezone">Time zone:</label>
    <select name="timezone">
        {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="Set">
</form>

{% include "dashboard/license.html" %}
</body>
</html>